language: java
jdk:
  - openjdk8
  - oraclejdk8

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script:
  - chmod +x ./gradlew build connectCheck

notifications:
  email:
    recipients:
      - cryharryk@gmail.com